name: "RealFlags CI"

on:
  push:
    branches:
      - master
      - hotfix
    paths:
      - 'RealFlags/Source/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'
  pull_request:
    paths:
      - 'RealFlags/Source/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'

concurrency:
  group: ci
  cancel-in-progress: true
  
jobs:
  name: "Test iOS"
    defaults:
      run:
        shell: "/usr/bin/arch -arch arm64e /bin/zsh {0}"
    env:
      DEVELOPER_DIR: "/Applications/Xcode_13.2.1.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=15.2,name=iPhone 13 Pro"
            name: "iOS 15.2"
          - destination: "OS=14.5,name=iPhone 12 Pro"
            name: "iOS 14.5"
          - destination: "OS=13.7,name=iPhone 11 Pro"
            name: "iOS 13.7"
          # - destination: "OS=12.4,name=iPhone Xs"
          #   name: "iOS 12.4"
          # - destination: "OS=11.4,name=iPhone 7"
          #   name: "iOS 11.4"
    steps:
      - uses: actions/checkout@v2
      - name: Build & Run Tests
        run: xcodebuild -scheme RealFlags-Package test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro'
