name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - uses: actions/checkout@v2
    - name: Build & Run Tests
      run: xcodebuild -scheme IndomioFlags-Package test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
